import { environment } from 'src/environments/environment.prod';


export const CONFIG = {
    NAME_LENGTH: 20,
    ADDRESS_LENGTH: 150,
    EMAIL_LENGTH: 55,
    PASSWORD_LENGTH: 30,
    PASSWORD_MIN: 8,
    PASSWORD_MAX: 16,
    MOBILE_LENGTH: 15,
    MOBILE_MIN_LENGTH: 8,
    WEB_LENGTH: 150,
    DESCRIPTION_NAME_LENGTH:250,
    MAX_KID: 2,
    MAX_ADULT: 2,
    MIN_KID: 1,
    NAME_MAX_LENGTH:50,
    MIN_ADULT: 1,
    MAX_PRICE: 5,
    MIN_PRICE: 1,
    MAX_QUANTITY:5,
    LIMIT: 10,
    MAX_IMAGE_HOTEL:10,
    NAME_LENGTH_TITLE:120,
    CARDLENGTH:16,
    DESCRIPTION_LENGTH: 500,
    MAXOTP_LENGTH: 4,
    MINOTP_LENGTH: 4,
    MAX_BATHROOM:2,
    NAME_MINLENGTH:1,
    DESCRIPTION_LENGTH_CMS:1000,
    B_NAME:20,
    B_DES:50,
    MAX_B:1,
    PRODUCT_MAX:50,
    PRODUCT_DESCRIPTION:500,
    NUMBER_LENGTH:5,
    MAX_PLAT_NUMBER:10,
    MIN_PLATE_NUMBER:4,
    MINCODE:5,
    MAXCODE:15,
    MINORDER:1,
    MAXORDER:5,
    ADDRESS_MAX_LENGTH:120,
    DATE_MAX_LENGTH:21,
    TITLE_LENGTH:50,

    BANNER_MIN_WIDTH:200,
    BANNER_MIN_HEIGHT:200,
    BANNER_MAX_WIDTH:1000,
    BANNER_MAX_HEIGHT:1000,

    CATEGORY_MIN_WIDTH:200,
    CATEGORY_MIN_HEIGHT:200,
    CATEGORY_MAX_WIDTH:600,
    CATEGORY_MAX_HEIGHT:600,

    BRAND_MIN_WIDTH:100,
    BRAND_MIN_HEIGHT:100,
    BRAND_MAX_WIDTH:2000,
    BRAND_MAX_HEIGHT:2000,



    PRODUCT_MIN_WIDTH:200,
    PRODUCT_MIN_HEIGHT:200,
    PRODUCT_MAX_WIDTH:600,
    PRODUCT_MAX_HEIGHT:600,


    PROFILE_MIN_WIDTH:200,
    PROFILE_MIN_HEIGHT:200,
    PROFILE_MAX_WIDTH:600,
    PROFILE_MAX_HEIGHT:600,



    
};
