import { environment } from 'src/environments/environment.prod';


export const CONFIG = {
    NAME_LENGTH: 20,
    ADDRESS_LENGTH: 150,
    EMAIL_LENGTH: 60,
    PASSWORD_LENGTH: 30,
    PASSWORD_MIN: 8,
    PASSWORD_MAX: 16,
    MOBILE_LENGTH: 15,
    MOBILE_MIN_LENGTH: 8,
    WEB_LENGTH: 150,
    DESCRIPTION_NAME_LENGTH:250,
    MAX_KID: 2,
    MAX_ADULT: 2,
    MIN_KID: 1,
    NAME_MAX_LENGTH:50,
    MIN_ADULT: 1,
    MAX_PRICE: 7,
    MIN_PRICE: 1,
    LIMIT: 10,
    MAX_IMAGE_HOTEL:10,
    NAME_LENGTH_TITLE:120,
    CARDLENGTH:16,
    DESCRIPTION_LENGTH: 500,
    MAXOTP_LENGTH: 4,
    MINOTP_LENGTH: 4,
    MAX_BATHROOM:2,
    NAME_MINLENGTH:2,
    DESCRIPTION_LENGTH_CMS:1000

};
